server:
  port: 8082

spring:
  application:
    name: routing
  artemis:
    mode: native #standalone broker, not native
    broker-url: tcp://localhost:61616  # usually dont want these in yaml
    user: admin
    password: admin
  jms:
    pub-sub-domain: false #configures as queue rather than topic